# Generated by Django 3.0.11 on 2021-01-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_question_placeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionplaceholder",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
